spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: info
    com.onepiece.otboo: debug
    org.springframework.security: trace
    # Spring Cache 관련 디버그 로그 활성화 (캐시 Hit/Miss 추적)
    org.springframework.cache: debug
    org.springframework.cache.interceptor: trace

otboo:
  security:
    csrf:
      ignored-paths:
