spring:
  application:
    name: otboo
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true      # H2 Console 사용 여부
      path: /h2-console  # H2 Console 접속 주소

otboo:
  jwt:
    access-token:
      secret: ${JWT_ACCESS_SECRET}
      expiration-ms: ${JWT_ACCESS_EXPIRATION_MS}
    refresh-token:
      secret: ${JWT_REFRESH_SECRET}
      expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}
    max-active-jwt-count: 1

api:
  kakao:
    rest-api-key: ${REST_API_KEY}

