spring:
  config:
    import: optional:file:.env[.properties]
  h2:
    console:
      enabled: false
  jpa:
    show-sql: false

logging:
  level:
    root: info
    com.onepiece.otboo: info
    org.springframework: info
    org.hibernate.SQL: off
