spring:
  config:
    import: optional:file:.env[.properties]
  h2:
    console:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:80}

logging:
  level:
    root: info
    com.onepiece.otboo: info
    org.springframework: info
    org.hibernate.SQL: off
otboo:
  security:
    cors:
      allowed-origins:
        - "http://otboo-lord-balencer-342590016.ap-northeast-2.elb.amazonaws.com"
        - "https://otboo-lord-balencer-342590016.ap-northeast-2.elb.amazonaws.com"
        - "http://localhost:3000"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
      allow-credentials: true
    csrf:
      ignored-paths:
    swagger:
      basic:
        enabled: true
        username: ${SWAGGER_BASIC_USERNAME}
        password: ${SWAGGER_BASIC_PASSWORD}