name: ci.yml
on:
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Secrets
      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
      JWT_ACCESS_EXPIRATION_MS: ${{ secrets.JWT_ACCESS_EXPIRATION_MS }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_REFRESH_EXPIRATION_MS: ${{ secrets.JWT_REFRESH_EXPIRATION_MS }}
      REST_API_KEY: ${{ secrets.REST_API_KEY }}
      MAIL_SENDER_EMAIL: ${{ secrets.MAIL_SENDER_EMAIL }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      TEMP_PASSWORD_VALIDITY_SECONDS: ${{ secrets.TEMP_PASSWORD_VALIDITY_SECONDS }}
      TEMP_PASSWORD_CHARSET: ${{ secrets.TEMP_PASSWORD_CHARSET }}
      TEMP_PASSWORD_SPECIAL_CHARSET: ${{ secrets.TEMP_PASSWORD_SPECIAL_CHARSET }}
      SERVICE_API_KEY: ${{ secrets.SERVICE_API_KEY}}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_PRESIGNED_URL_EXPIRATION: ${{ secrets.AWS_PRESIGNED_URL_EXPIRATION }}
      PROFILE_PREFIX: ${{ secrets.PROFILE_PREFIX }}
      CLOTHES_PREFIX: ${{ secrets.CLOTHES_PREFIX }}
      DEFAULT_LOCATION_NAME: ${{ secrets.DEFAULT_LOCATION_NAME }}
      OAUTH2_GOOGLE_CLIENT_ID: ${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}
      OAUTH2_GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}
      OAUTH2_KAKAO_CLIENT_ID: ${{ secrets.OAUTH2_KAKAO_CLIENT_ID }}
      OAUTH2_KAKAO_CLIENT_SECRET: ${{ secrets.OAUTH2_KAKAO_CLIENT_SECRET }}
      # Variables
      ASYNC_THREAD_POOL_DEFAULT_CORE_SIZE: ${{ vars.ASYNC_THREAD_POOL_DEFAULT_CORE_SIZE }}
      ASYNC_THREAD_POOL_DEFAULT_MAX_SIZE: ${{ vars.ASYNC_THREAD_POOL_DEFAULT_MAX_SIZE }}
      ASYNC_THREAD_POOL_DEFAULT_QUEUE_CAPACITY: ${{ vars.ASYNC_THREAD_POOL_DEFAULT_QUEUE_CAPACITY }}
      ASYNC_THREAD_POOL_DEFAULT_KEEP_ALIVE: ${{ vars.ASYNC_THREAD_POOL_DEFAULT_KEEP_ALIVE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run tests with coverage
        env:
            AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: ./gradlew clean test jacocoMergedReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/merged/jacoco.xml
